<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAR8Kime\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAR8Kime/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAR8Kime.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAR8Kime\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAR8Kime\App_KernelDevDebugContainer([
    'container.build_hash' => 'AR8Kime',
    'container.build_id' => '13f3bee2',
    'container.build_time' => 1678365868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAR8Kime');
