<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyvHlLr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyvHlLr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyvHlLr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyvHlLr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyvHlLr\App_KernelDevDebugContainer([
    'container.build_hash' => 'XyvHlLr',
    'container.build_id' => 'ebea6de7',
    'container.build_time' => 1678377380,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyvHlLr');
