<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNVtzLb4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNVtzLb4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNVtzLb4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNVtzLb4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNVtzLb4\App_KernelDevDebugContainer([
    'container.build_hash' => 'NVtzLb4',
    'container.build_id' => 'b10aebd7',
    'container.build_time' => 1678376452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNVtzLb4');
